Task A



In [6]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

In [40]:
def standard(X):
    return (X - np.mean(X,axis=0))/np.std(X,axis=0)

In [42]:
X = np.random.randn(3,4)
Xs=standard(X)
print(Xs)
np.mean(Xs,axis=0),np.std(Xs,axis=0)

[[ 0.46747696 -1.2427537  -0.98384345  1.19295294]
 [-1.38963595  0.03684931 -0.38787316 -1.2542359 ]
 [ 0.92215899  1.20590438  1.37171661  0.06128296]]


(array([-1.11022302e-16,  2.22044605e-16, -7.40148683e-17, -2.54426110e-17]),
 array([1., 1., 1., 1.]))

Task B

In [111]:
P=np.arange(2,16).reshape(-1,2)
Q=np.arange(5,40,3).reshape(-1,2)
print(P)
print(Q)

[[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 5  8]
 [11 14]
 [17 20]
 [23 26]
 [29 32]
 [35 38]]


In [117]:
print(P.shape)
print(Q.shape)
print(P[:,np.newaxis,:].shape)
print(Q[np.newaxis,:].shape)
print(P[:,np.newaxis,:])
print(Q[np.newaxis,:])

(7, 2)
(6, 2)
(7, 1, 2)
(1, 6, 2)
[[[ 2  3]]

 [[ 4  5]]

 [[ 6  7]]

 [[ 8  9]]

 [[10 11]]

 [[12 13]]

 [[14 15]]]
[[[ 5  8]
  [11 14]
  [17 20]
  [23 26]
  [29 32]
  [35 38]]]


In [114]:
diff = P[:,np.newaxis,:] - Q[np.newaxis,:,:]
print(diff.shape)
print(diff)

(7, 6, 2)
[[[ -3  -5]
  [ -9 -11]
  [-15 -17]
  [-21 -23]
  [-27 -29]
  [-33 -35]]

 [[ -1  -3]
  [ -7  -9]
  [-13 -15]
  [-19 -21]
  [-25 -27]
  [-31 -33]]

 [[  1  -1]
  [ -5  -7]
  [-11 -13]
  [-17 -19]
  [-23 -25]
  [-29 -31]]

 [[  3   1]
  [ -3  -5]
  [ -9 -11]
  [-15 -17]
  [-21 -23]
  [-27 -29]]

 [[  5   3]
  [ -1  -3]
  [ -7  -9]
  [-13 -15]
  [-19 -21]
  [-25 -27]]

 [[  7   5]
  [  1  -1]
  [ -5  -7]
  [-11 -13]
  [-17 -19]
  [-23 -25]]

 [[  9   7]
  [  3   1]
  [ -3  -5]
  [ -9 -11]
  [-15 -17]
  [-21 -23]]]


In [122]:
Dt = np.sqrt(np.sum(diff**2,axis=2))
print(Dt)
print(Dt.shape)

[[ 5.83095189 14.2126704  22.6715681  31.144823   39.62322551 48.10405388]
 [ 3.16227766 11.40175425 19.84943324 28.31960452 36.79673899 45.27692569]
 [ 1.41421356  8.60232527 17.02938637 25.49509757 33.9705755  42.44997055]
 [ 3.16227766  5.83095189 14.2126704  22.6715681  31.144823   39.62322551]
 [ 5.83095189  3.16227766 11.40175425 19.84943324 28.31960452 36.79673899]
 [ 8.60232527  1.41421356  8.60232527 17.02938637 25.49509757 33.9705755 ]
 [11.40175425  3.16227766  5.83095189 14.2126704  22.6715681  31.144823  ]]
(7, 6)


In [123]:
def pairwise (P,Q):
    diff = P[:,np.newaxis,:]-Q[np.newaxis,:,:]
    D = np.sqrt(np.sum(diff**2,axis=2))
    return D

In [124]:
D = pairwise (P,Q)
print(D)

[[ 5.83095189 14.2126704  22.6715681  31.144823   39.62322551 48.10405388]
 [ 3.16227766 11.40175425 19.84943324 28.31960452 36.79673899 45.27692569]
 [ 1.41421356  8.60232527 17.02938637 25.49509757 33.9705755  42.44997055]
 [ 3.16227766  5.83095189 14.2126704  22.6715681  31.144823   39.62322551]
 [ 5.83095189  3.16227766 11.40175425 19.84943324 28.31960452 36.79673899]
 [ 8.60232527  1.41421356  8.60232527 17.02938637 25.49509757 33.9705755 ]
 [11.40175425  3.16227766  5.83095189 14.2126704  22.6715681  31.144823  ]]


Task C

In [287]:
d = 2
xn = np.array(range(d))
theta1 = np.random.randint(0,25,size=(d,d+1))
theta2 = np.random.randint(0,25,size=(d,d+1))

In [322]:
first = (2*np.pi)**(d/2)
p1_1 = 1/((first*(np.linalg.det(theta1[:,1:d+1])))**0.5)
p1_2 = 1/((first*(np.linalg.det(theta2[:,1:d+1])))**0.5)

In [349]:
p2_11=-0.5*((xn-theta1[:,0])).reshape(1,2)
print(p2_11)
p2_12=np.linalg.inv(theta1[:,1:d+1])
print(p2_12)
p2_13=(xn-theta1[:,0]).reshape(2,1)
print(p2_13)

p2_21=-0.5*((xn-theta2[:,0])).reshape(1,2)
p2_22=np.linalg.inv(theta2[:,1:d+1])
p2_23=(xn-theta2[:,0]).reshape(2,1)
p2_1=np.exp((p2_11.dot(p2_12)).dot(p2_13))[0,0]
p2_2=np.exp((p2_21.dot(p2_22)).dot(p2_23))[0,0]
print(p2_2)

[[10. 11.]]
[[ 0.09019608 -0.05490196]
 [-0.05098039  0.0745098 ]]
[[-20]
 [-22]]
1.0627178717786013e-05


In [357]:
p1 = p1_1*p2_1
p2 = p1_2*p2_2
p = np.array([p1,p2])
np.argmax(p)

1

In [358]:
def likelihood (xn,d,theta1,theta2):
    first = (2*np.pi)**(d/2)
    p1_1 = 1/((first*(np.linalg.det(theta1[:,1:d+1])))**0.5)
    p1_2 = 1/((first*(np.linalg.det(theta2[:,1:d+1])))**0.5)
    p2_11=-0.5*((xn-theta1[:,0])).reshape(1,2)
    p2_12=np.linalg.inv(theta1[:,1:d+1])
    p2_13=(xn-theta1[:,0]).reshape(2,1)
    p2_21=-0.5*((xn-theta2[:,0])).reshape(1,2)
    p2_22=np.linalg.inv(theta2[:,1:d+1])
    p2_23=(xn-theta2[:,0]).reshape(2,1)
    p2_1=np.exp((p2_11.dot(p2_12)).dot(p2_13))[0,0]
    p2_2=np.exp((p2_21.dot(p2_22)).dot(p2_23))[0,0]
    p1 = p1_1*p2_1
    p2 = p1_2*p2_2
    p = np.array([p1,p2])
    return np.argmax(p) + 1

In [359]:
print (likelihood(xn,d,theta1,theta2))

2
